export default function Head() {
  return (
    <>
      <title>Create App</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <meta name="author" content="John Doe" />
      <link rel="icon" href="images/icons/favicon.ico" />
      <link rel="manifest" href="manifest.json" />

      {/*  ios support */}
      <link rel="apple-touch-icon" href="images/icons/icon-72x72.png" />
      <link rel="apple-touch-icon" href="images/icons/icon-96x96.png" />
      <link rel="apple-touch-icon" href="images/icons/icon-128x128.png" />
      <link rel="apple-touch-icon" href="images/icons/icon-144x144.png" />
      <link rel="apple-touch-icon" href="images/icons/icon-152x152.png" />
      <link rel="apple-touch-icon" href="images/icons/icon-192x192.png" />
      <link rel="apple-touch-icon" href="images/icons/icon-384x384.png" />
      <link rel="apple-touch-icon" href="images/icons/icon-512x512.png" />
      <meta name="apple-mobile-web-app-status-bar" content="#ffffff" />
      <meta name="theme-color" content="#ffffff" />
    </>
  );
}
